# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170518_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
